version: '3'
services:
  jctgbot:
    build:
      context: ./jctgbot
    environment:
      - NODE_ENV=production
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: telegram-bot
